server:
  port: 8001

spring:
  application:
    name: spring-ehcache

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/spring-ehcache?useSSL=false
    username: root
    password: T0kh@66053
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: TRACE